### ISSUE TITLE
Can't record

### ISSUE THREAD

**Issue by Chinggis6** [Toqozz/slip#2]
Hello, thank you for the utility, it's very useful and **quick**, but even though I can take screenshots with `slip --screnshot` or `-s`, recording is not working for me.

Here's the error (output):

    /usr/bin/slip: line 146: kill: (13021) - No such process

I've copied the (example) config file directly from here (GitHub), and created the `vid` and `img` directories in my home folder.

I've also noticed that it does create `/tmp/slip_record.pid` file with a numeric value.

I remove that file myself to *stop* `slip`. I use it over `roti`.

I also have `ffmeg` installed along with `maim` and `slop`.

**PS**

Seeing copying the link to primary selection (instead of clipboard) option commented in the file and uncommenting it was what I first decided to edit `/usr/bin/slip` for :)

**Comment by Toqozz** [comment]
Strange, how exactly are you trying to stop recording?  The intended way is to open slip again and when it detects that recording is happening you have the option to stop it. 

Just thought of something, give me a second to check.

**Comment by Chinggis6** [comment]
I run `slip` again in the terminal (`fish` + `urxvt`) and it shows up `rofi`, then I select the option `stop` and it ouputs *the error* on the screen (of terminal).

**Comment by Toqozz** [comment]
Okay, so the way I understand it (from your original post) is that you're manually removing the pid file `/tmp/slip_record.pid` to get slip to stop recording? 

This won't actually stop recording because slip uses the pid file to stop recording, you pretty much need to stop recording through slip.  (I have just added an option to do so from the command line, use it like `slip -q`, couldn't think of a better flag).

**Comment by Toqozz** [comment]
Otherwise, ffmpeg must be being closed some other way.  If this happens, then `slip` will actually never be able to "finish recording" on its own because the file never gets removed.  I'll try fix that up now :).

**Comment by Chinggis6** [comment]
Again,

    ./slip: line 147: kill: (13962) - No such process

I used `-q` this time, as well.

It seems something somewhere in the file cannot create the process properly, or the process dies soon (b/c file has value).

Btw, I downloaded it from AUR first, but now tried directly from the script (w/o installing).

**Comment by Toqozz** [comment]
It's trying to kill the ffmpeg process (13962), but `no such process`.  Could you do the following steps?

- Remove /tmp/slip_record.pid (`rm /tmp/slip_record.pid`)
- Start recording (`./slip --record`)
- Stop recording (`./slip --quit`)

Sorry if this is what you're currently doing, just want to make sure we're on the same page.

**Comment by Chinggis6** [comment]
./slip: line 147: kill: (15985) - No such process

Exactly the same thing.

**Comment by Chinggis6** [comment]
Btw, `SOUND` is `1` in the `config`, while `0` in the script.

I made both zero, nothing changed.

**Comment by Toqozz** [comment]
Could you please let me know the output of `ffmpeg -f x11grab -video_size "500x500" -framerate 60 -i ":0" -c:v libx264 -preset ultrafast test.mkv`.

Or, if you're using sound, `ffmpeg -f pulse -i 1 -f x11grab -video_size "500x500" -framerate 60 -i ":0" -c:v libx264 -preset ultrafast test.mkv`.

Specifically I want to know if it errors and closes itself.

**Comment by Chinggis6** [comment]
Both commands worked well, filled the standard output, and created the file (`.mkv`) :confused:.

**Comment by Toqozz** [comment]
All that slip does is run that ffmpeg command (or very similar), record ffmpeg's pid, and then later on issues `kill` on it; I'm a bit confused here.

The only further debugging I can offer you is to check `top` or `htop` for `ffmpeg` after starting a recording to find out if ffmpeg is crashing / exiting early.  You can also check the pid of the ffmpeg command and see if `/tmp/slip_record.pid` reflects that, though I don't see why it would record the wrong pid at any point.

Please let me know the results.

**Comment by Toqozz** [comment]
Does your environment have `$DISPLAY` set?

```
[~] -->   echo $DISPLAY
:0
```

**Comment by Chinggis6** [comment]
Yes, $DISPLAY is `:0`.

`ffmpeg` is not shown on `htop`. I think it quits after `slip` is *done*.

I couldn't figure it out anyhow, but thanks for the support so far :)

**Comment by Toqozz** [comment]
If you are recording with sound, could you remove the `&> /dev/null &` at the end of `line 90`?
If you are recording without sound, could you remove the `&> /dev/null &` at the end of `line 92`?

Then try to record again, noting the output from slip.

This will break it, but we'll at least see what's going on with ffmpeg.

**Comment by Chinggis6** [comment]
Problem solved, my bad, I should have created `slip` subdirectory inside the `vid` directory (`mkdir -p ~/vid/slip`).

Removing that part of the code, could help me finding the issue.

Thank you very much for that.

Some few personal notes of worth, that may help future users, I noted that `config` file differs from the script file, that is the contents of `/usr/bin/slip` where `$IMAGES` and `$VIDEOS` are `$HOME/Pictures` and `$HOME/Videos` respectively, while in the config the values are $HOME/vid/**slip** and $HOME/vid/**slip**, that was exactly what confused me, one extra directory. Moreover, I'd suggest putting the example configs in `/usr/share/doc` keeping if it's not already, and creating the user-wide `~/.config/slip` directory by default.

But again, I admit, I should have been more careful with reading the variable's value and creating the directories manually.

That's it, I'm happy now :)

Thanks again :+1:

**Comment by Chinggis6** [comment]
Oh, I accidentally deleted my comment :)

**Comment by Chinggis6** [comment]
Oh, I accidentally deleted my previous comment.

Basically it was about:

#### /usr/bin/slip
VIDEOS = $HOME/Videos

#### $HOME/.config/slip/config
VIDEOS = $HOME/vid/**slip**

One more directory to create.

    mkdir -p ~/vid/slip

**Comment by Toqozz** [comment]
Woo!  Thanks for your patience.

You're right about the config differences, they're a bit lazy and I'll change them when I next get the chance.  About creating the directory by default; slip can be run without a config file -- the defaults are pretty sane.  I wouldn't want to clog up anyone's `~/.config/` directory unless they wanted some further customization.  

I'll try make the defaults better in case of lack of a config file, and I'll fix the discrepancies between the config and the default.

I may put the example config in `/usr/share/doc` when installing from the AUR, but again I worry about tossing it in by default because of reasons discussed earlier.

Thanks!

(Here's the comment before it was removed: http://i.imgur.com/2Fpsy58.png)
