### ISSUE TITLE
can we have a --no-upload option please?

### ISSUE THREAD

**Issue by ducklin5** [Toqozz/slip#6]
As the title says, this is more of a feature request than an issue

**Comment by Toqozz** [comment]
This was actually supposed to be implemented before but it seems the thread got sidetracked by gif support instead.

So your intended usecase would be slip --screenshot --no-upload from the command line?  Or would you prefer some form of interaction through dmenu as well (probably turned on by a config option)?

**Comment by ducklin5** [comment]
I think a simple --no-upload would be good, which the upload function can check if the tag exists anf if it does the function is bypassed no matter what option is picked in dmenu

**Comment by ducklin5** [comment]
I think a simple --no-upload would be good, which the upload function can check if the tag exists anf if it does the function is bypassed no matter what option is picked in dmenu

**Comment by Toqozz** [comment]
I've pushed a new version with a --no-upload option.  You can use it in the folliwng ways:

`slip --no-upload`: opens selection menu, and doesn't upload the result.
`slip --screenshot --no-upload`: takes a screenshot, and doesn't upload.
`NOUPLOAD=1` in `config`: enables the above flags for every screenshot / gif.

Test it out if you get the chance!  I'll push the new version to the aur soon.
