### ISSUE TITLE
gfycat upload doesn't work

### ISSUE THREAD

**Issue by oblitum** [Toqozz/slip#8]
It seems the gfycat api isn't being used right, I get the URLs but they always have no content, even after a very long time.

**Comment by oblitum** [comment]
Nevermind. My god gfycat processing time is absurd, even when sending processed gifs.

**Comment by Toqozz** [comment]
Yup, see readme.

**Comment by oblitum** [comment]
I'm searching some better web sites to host gifs, and https://imgbb.com looks really nice, you can upload a gif up to 32MB, and it doesn't convert it into a video of low quality like gfycat does (even the HD playback is blurry), it simply servers the original file, they have an api (https://api.imgbb.com/), and on upload you can even set expiration time, which is great if you wish a gif up just for a couple of minutes/hours.

Another good one is https://uguu.se/, which serves files up to 100MB temporarily for 24h.

**Comment by Toqozz** [comment]
https://imgbb.com looks nice, I will consider implementing it, or would happily accept a pull request.
